### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by whippingdot** [Bogdanp/awesome-advent-of-code#1134]
How do you decide what repos go up here?

**Comment by Bogdanp** [comment]
See: https://github.com/Bogdanp/awesome-advent-of-code/blob/master/CONTRIBUTING.md

Anybody with a repo can make a PR to add it.

**Comment by whippingdot** [comment]
even if personally i think my repo is trash - and if i only have one repo for all aocs?

**Comment by Bogdanp** [comment]
Yup. If you want to add it, you can.
