### ISSUE TITLE
Years before 2018 welcome?

### ISSUE THREAD

**Issue by jeroenheijmans** [Bogdanp/awesome-advent-of-code#1324]
I hesitated to create fresh pre-2018 .md files because there might be a build action or specific gotcha in creating one? If there isn't, I'd be happy to create a base file for those earlier years, same setup as the newer ones?

Thx for a great repo!

**Comment by Bogdanp** [comment]
Thanks for asking first. I've let people update previous years, but I mostly think of them as archives of this repo specifically. So, in that sense, I don't think we should be adding previous years (plus I don't want the added maintenance burden, tbh).
