### ISSUE TITLE
`last commit` badge not updating for my repo

### ISSUE THREAD

**Issue by two-six** [Bogdanp/awesome-advent-of-code#1523]
It seems that my `last commit` badge is not updating for some reason:

![image](https://user-images.githubusercontent.com/92624829/206872506-bbeee781-2a20-479e-954e-0b5844b8b64d.png)

![image](https://user-images.githubusercontent.com/92624829/206872538-286eb259-8515-4869-b3dd-3a10ac79ada7.png)

**Comment by Bogdanp** [comment]
Looks like your last commit resolved the issue.
