### ISSUE TITLE
Polyglot repositories

### ISSUE THREAD

**Issue by AlexAegis** [Bogdanp/awesome-advent-of-code#166]
Currently, someone who looks for a repository in a certain language will overlook the ones in the polyglot section. Marking them with the languages isn't a good solution because you have to look in two sections for it.

I suggest removing the restriction of not being able to add our codebases into multiple language sections.

**Comment by Bogdanp** [comment]
I would potentially be willing to relax the limit to 2 or 3 languages per repo and get rid of the polyglot section. I'm curious what others think so I'll leave this open for a bit.
