### ISSUE TITLE
Support for community contest

### ISSUE THREAD

**Issue by psmyrdek** [Bogdanp/awesome-advent-of-code#1672]
Hi folks,

Thanks for the amazing effort around this repository. As a builder of [Advent of Frontend](https://www.opanujfrontend.pl/advent) I wanted to ask if you'd be interested in featuring community projects like mine.

Feel free to share honest feedback - I don't want to force any PR if you think it's not the right idea.

Cheers

**Comment by Bogdanp** [comment]
If there is an English version then feel free to make a PR to add it to the list!
