### ISSUE TITLE
Commit badges are not being updated for previous years

### ISSUE THREAD

**Issue by ndunnett** [Bogdanp/awesome-advent-of-code#1837]
Not sure if this is intended or not, but it seems the action to update commit badges is only working on the repos for current year in README.md. If you have a look in [2022.md](/Bogdanp/awesome-advent-of-code/blob/master/2022.md) for instance there are several entries without badges.

**Comment by Bogdanp** [comment]
Yeah this is a known issue. A PR would be welcome.

**Comment by ndunnett** [comment]
> Yeah this is a known issue. A PR would be welcome.

I tried the naive change in a fork by using a matrix strategy to run the `update-badge` action on multiple files but ran into GH API rate limits. I can work around that by rewriting that action to use GraphQL queries to get repo information in bulk instead of using individual REST requests, would you be happy for me to do that?
