### ISSUE TITLE
Reaching API rate limits

### ISSUE THREAD

**Issue by ndunnett** [Bogdanp/awesome-advent-of-code#1839]
Looks like the new badge automation I wrote is hitting secondary rate limits:

https://github.com/Bogdanp/awesome-advent-of-code/actions/runs/8776567228
https://github.com/Bogdanp/awesome-advent-of-code/actions/runs/8592640932

When I get some time I'll have a look.

**Comment by Bogdanp** [comment]
Maybe a quick fix would be to limit the job to the (rolling) past 3y.
