### ISSUE TITLE
Updating badges more often

### ISSUE THREAD

**Issue by jugendhacker** [Bogdanp/awesome-advent-of-code#633]
I think the badges should be updated more often because I for example uploaded my solution already, but the cron job for the update will run the next time in around 18 hours, so for 18 hours now the badge is wrong. Maybe update them every hour?

**Comment by Bogdanp** [comment]
I think the current frequency is fine and I'm reluctant to increase it because it would mean hitting the GH API more, which seems wasteful. Also, I currently merge new PRs in batches about twice a day which ends up triggering the job as well.

**Comment by mebeim** [comment]
I'm curious, why not just let shields.io handle this I.E. using `https://img.shields.io/github/last-commit/$USER/$REPO` instead of generating those manually? Also, is there any reason why the badges are yellow even though the last commit on almost every badge is today? If I am not mistaken those used to show up as green.

**Comment by Bogdanp** [comment]
> I'm curious, why not just let shields.io handle this I.E. using https://img.shields.io/github/last-commit/$USER/$REPO instead of generating those manually?

See https://github.com/Bogdanp/awesome-advent-of-code/issues/152 .

>  Also, is there any reason why the badges are yellow even though the last commit on almost every badge is today? If I am not mistaken those used to show up as green.

This is a bug I haven't had a chance to look into yet. I'll gladly accept any help on that front!

**Comment by casperdcl** [comment]
what's wrong with using `https://img.shields.io/badge/dynamic/json?label=last%20commit&query=%24.0.commit.author.date&url=https%3A%2F%2Fapi.github.com%2Frepos%2F{USER}%2F{REPO}%2Fcommits%3Fper_page%3D1`? It would fix #152 and replace #389 - no more complicated github actions etc needed.

[![](https://img.shields.io/badge/dynamic/json?label=last%20commit&query=%24.0.commit.author.date&url=https%3A%2F%2Fapi.github.com%2Frepos%2FBogdanp%2Fawesome-advent-of-code%2Fcommits%3Fper_page%3D1)](/Bogdanp/awesome-advent-of-code)
