### ISSUE TITLE
Python Solutions

### ISSUE THREAD

**Issue by sergiomartins8** [Bogdanp/awesome-advent-of-code#670]
Hello 👋  

Feel free to add mine to the python solutions if you see fit
https://github.com/sergiomartins8/advent-of-code-2020

Cheers!

**Comment by Bogdanp** [comment]
Please follow the instructions in the [CONTRIBUTING.md](https://github.com/Bogdanp/awesome-advent-of-code/blob/9320d1d4aab562a2f0a9339691e58ddd30ba856a/CONTRIBUTING.md) file if you want to add your repo to the list. Thanks!
